server:
  port: 8098



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 690501LJK



  redis:
    port: 6379
    host: 127.0.0.1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true